# Generated by Django 6.0.5 on 2026-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g. 'fas fa-book')", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Clubs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MD ABU SALEHIN', max_length=200)),
                ('title', models.CharField(default='Web Developer & System Architect', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Short bio for the developer page')),
                ('portfolio_url', models.URLField(default='https://mdsalehin.pro.bd/')),
                ('image_url', models.URLField(default='https://mdsalehin.pro.bd/me.jpg')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Developer Info',
            },
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
